spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryolytix
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: USER
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
